<?php

declare(strict_types=1);

use App\Enums\RouteNodeActionType;
use App\Enums\RouteNodeKind;

/**
 * Декларативные маршруты для админского API.
 *
 * Эти маршруты загружаются автоматически и имеют приоритет над маршрутами из БД.
 * Используются для статических системных маршрутов, которые не должны изменяться через UI.
 *
 * @return array<int, array<string, mixed>>
 */
return [
    // Группа для админских маршрутов
    // Полный префикс: api/v1/admin
    // Middleware группа 'api' применяется в RouteServiceProvider через Route::middleware('api')
    // Middleware: jwt.auth, throttle:api
    // sort_order = -998 (третий в порядке регистрации)
    [
        'kind' => RouteNodeKind::GROUP,
        'sort_order' => -998,
        'prefix' => 'api/v1/admin',
        'middleware' => ['api','jwt.auth', 'throttle:api'],
        'children' => [
            // Auth & Utils
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/auth/current',
                'methods' => ['GET'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Auth\CurrentUserController@show',
                'name' => 'admin.v1.auth.current',
                'middleware' => ['no-cache-auth'],
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/utils/slugify',
                'methods' => ['GET'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\UtilsController@slugify',
                'name' => 'admin.v1.utils.slugify',
            ],
            // Templates (full CRUD)
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/templates',
                'methods' => ['GET'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\TemplateController@index',
                'name' => 'admin.v1.templates.index',
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/templates/{name}',
                'methods' => ['GET'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\TemplateController@show',
                'name' => 'admin.v1.templates.show',
                'where' => ['name' => '.*'],
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/templates',
                'methods' => ['POST'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\TemplateController@store',
                'name' => 'admin.v1.templates.store',
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/templates/{name}',
                'methods' => ['PUT'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\TemplateController@update',
                'name' => 'admin.v1.templates.update',
                'where' => ['name' => '.*'],
            ],
            // Post Types (full CRUD)
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/post-types',
                'methods' => ['POST'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\PostTypeController@store',
                'name' => 'admin.v1.post-types.store',
                'middleware' => ['App\Http\Middleware\EnsureCanManagePostTypes'],
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/post-types',
                'methods' => ['GET'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\PostTypeController@index',
                'name' => 'admin.v1.post-types.index',
                'middleware' => ['App\Http\Middleware\EnsureCanManagePostTypes'],
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/post-types/{id}',
                'methods' => ['GET'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\PostTypeController@show',
                'name' => 'admin.v1.post-types.show',
                'middleware' => ['App\Http\Middleware\EnsureCanManagePostTypes'],
                'where' => ['id' => '[0-9]+'],
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/post-types/{id}',
                'methods' => ['PUT'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\PostTypeController@update',
                'name' => 'admin.v1.post-types.update',
                'middleware' => ['App\Http\Middleware\EnsureCanManagePostTypes'],
                'where' => ['id' => '[0-9]+'],
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/post-types/{id}',
                'methods' => ['DELETE'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\PostTypeController@destroy',
                'name' => 'admin.v1.post-types.destroy',
                'middleware' => ['App\Http\Middleware\EnsureCanManagePostTypes'],
                'where' => ['id' => '[0-9]+'],
            ],
            // Form Configs
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/post-types/{post_type_id}/form-config/{blueprint}',
                'methods' => ['GET'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\FormConfigController@show',
                'name' => 'admin.v1.post-types.form-config.show',
                'middleware' => ['App\Http\Middleware\EnsureCanManagePostTypes'],
                'where' => ['post_type_id' => '[0-9]+'],
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/post-types/{post_type_id}/form-config/{blueprint}',
                'methods' => ['PUT'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\FormConfigController@update',
                'name' => 'admin.v1.post-types.form-config.update',
                'middleware' => ['App\Http\Middleware\EnsureCanManagePostTypes'],
                'where' => ['post_type_id' => '[0-9]+'],
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/post-types/{post_type_id}/form-config/{blueprint}',
                'methods' => ['DELETE'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\FormConfigController@destroy',
                'name' => 'admin.v1.post-types.form-config.destroy',
                'middleware' => ['App\Http\Middleware\EnsureCanManagePostTypes'],
                'where' => ['post_type_id' => '[0-9]+'],
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/post-types/{post_type_id}/form-configs',
                'methods' => ['GET'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\FormConfigController@indexByPostType',
                'name' => 'admin.v1.post-types.form-configs.index',
                'middleware' => ['App\Http\Middleware\EnsureCanManagePostTypes'],
                'where' => ['post_type_id' => '[0-9]+'],
            ],
            // Entries (full CRUD + soft-delete/restore)
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/entries/statuses',
                'methods' => ['GET'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\EntryController@statuses',
                'name' => 'admin.v1.entries.statuses',
                'middleware' => ['can:viewAny,App\Models\Entry'],
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/entries',
                'methods' => ['GET'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\EntryController@index',
                'name' => 'admin.v1.entries.index',
                'middleware' => ['can:viewAny,App\Models\Entry'],
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/entries',
                'methods' => ['POST'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\EntryController@store',
                'name' => 'admin.v1.entries.store',
                'middleware' => ['can:create,App\Models\Entry'],
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/entries/{id}',
                'methods' => ['GET'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\EntryController@show',
                'name' => 'admin.v1.entries.show',
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/entries/{entry}/preview',
                'methods' => ['GET'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\EntryPreviewController@show',
                'name' => 'admin.v1.entries.preview',
                'where' => ['entry' => '[0-9]+'],
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/entries/{id}',
                'methods' => ['PUT'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\EntryController@update',
                'name' => 'admin.v1.entries.update',
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/entries/{id}',
                'methods' => ['DELETE'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\EntryController@destroy',
                'name' => 'admin.v1.entries.destroy',
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/entries/{id}/restore',
                'methods' => ['POST'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\EntryController@restore',
                'name' => 'admin.v1.entries.restore',
            ],
            // Taxonomies (with middleware group)
            [
                'kind' => RouteNodeKind::GROUP,
                'middleware' => ['can:manage.taxonomies'],
                'children' => [
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/taxonomies',
                        'methods' => ['GET'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\TaxonomyController@index',
                        'name' => 'admin.v1.taxonomies.index',
                    ],
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/taxonomies',
                        'methods' => ['POST'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\TaxonomyController@store',
                        'name' => 'admin.v1.taxonomies.store',
                    ],
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/taxonomies/{id}',
                        'methods' => ['GET'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\TaxonomyController@show',
                        'name' => 'admin.v1.taxonomies.show',
                    ],
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/taxonomies/{id}',
                        'methods' => ['PUT'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\TaxonomyController@update',
                        'name' => 'admin.v1.taxonomies.update',
                    ],
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/taxonomies/{id}',
                        'methods' => ['DELETE'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\TaxonomyController@destroy',
                        'name' => 'admin.v1.taxonomies.destroy',
                    ],
                ],
            ],
            // Terms (with middleware group)
            [
                'kind' => RouteNodeKind::GROUP,
                'middleware' => ['can:manage.terms'],
                'children' => [
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/taxonomies/{taxonomy}/terms/tree',
                        'methods' => ['GET'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\TermController@tree',
                        'name' => 'admin.v1.taxonomies.terms.tree',
                        'where' => ['taxonomy' => '[0-9]+'],
                    ],
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/taxonomies/{taxonomy}/terms',
                        'methods' => ['GET'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\TermController@indexByTaxonomy',
                        'name' => 'admin.v1.taxonomies.terms.index',
                        'where' => ['taxonomy' => '[0-9]+'],
                    ],
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/taxonomies/{taxonomy}/terms',
                        'methods' => ['POST'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\TermController@store',
                        'name' => 'admin.v1.taxonomies.terms.store',
                        'where' => ['taxonomy' => '[0-9]+'],
                    ],
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/terms/{term}',
                        'methods' => ['GET'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\TermController@show',
                        'name' => 'admin.v1.terms.show',
                    ],
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/terms/{term}',
                        'methods' => ['PUT'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\TermController@update',
                        'name' => 'admin.v1.terms.update',
                    ],
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/terms/{term}',
                        'methods' => ['DELETE'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\TermController@destroy',
                        'name' => 'admin.v1.terms.destroy',
                    ],
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/entries/{entry}/terms',
                        'methods' => ['GET'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\EntryTermsController@index',
                        'name' => 'admin.v1.entries.terms.index',
                    ],
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/entries/{entry}/terms/sync',
                        'methods' => ['PUT'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\EntryTermsController@sync',
                        'name' => 'admin.v1.entries.terms.sync',
                    ],
                ],
            ],
            // Media (with middleware groups)
            [
                'kind' => RouteNodeKind::GROUP,
                'middleware' => ['can:viewAny,App\Models\Media'],
                'children' => [
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/media/config',
                        'methods' => ['GET'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\MediaController@config',
                        'name' => 'admin.v1.media.config',
                        'middleware' => ['throttle:60,1'],
                    ],
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/media',
                        'methods' => ['GET'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\MediaController@index',
                        'name' => 'admin.v1.media.index',
                        'middleware' => ['throttle:60,1'],
                    ],
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/media/{media}',
                        'methods' => ['GET'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\MediaController@show',
                        'name' => 'admin.v1.media.show',
                        'middleware' => ['throttle:60,1'],
                    ],
                ],
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/media',
                'methods' => ['POST'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\MediaController@store',
                'name' => 'admin.v1.media.store',
                'middleware' => ['can:create,App\Models\Media', 'throttle:20,1'],
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/media/bulk',
                'methods' => ['POST'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\MediaController@bulkStore',
                'name' => 'admin.v1.media.bulkStore',
                'middleware' => ['can:create,App\Models\Media', 'throttle:20,1'],
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/media/{media}',
                'methods' => ['PUT'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\MediaController@update',
                'name' => 'admin.v1.media.update',
                'middleware' => ['throttle:20,1'],
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/media/bulk',
                'methods' => ['DELETE'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\MediaController@bulkDestroy',
                'name' => 'admin.v1.media.bulkDestroy',
                'middleware' => ['throttle:20,1'],
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/media/bulk/restore',
                'methods' => ['POST'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\MediaController@bulkRestore',
                'name' => 'admin.v1.media.bulkRestore',
                'middleware' => ['throttle:20,1'],
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/media/bulk/force',
                'methods' => ['DELETE'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\MediaController@bulkForceDestroy',
                'name' => 'admin.v1.media.bulkForceDestroy',
                'middleware' => ['throttle:20,1'],
            ],
            // Blueprints (full CRUD + dependencies/embeddable)
            [
                'kind' => RouteNodeKind::GROUP,
                'prefix' => 'blueprints',
                'children' => [
                    // CRUD Blueprint
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/',
                        'methods' => ['GET'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\BlueprintController@index',
                        'name' => 'admin.v1.blueprints.index',
                    ],
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/',
                        'methods' => ['POST'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\BlueprintController@store',
                        'name' => 'admin.v1.blueprints.store',
                    ],
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/{blueprint}',
                        'methods' => ['GET'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\BlueprintController@show',
                        'name' => 'admin.v1.blueprints.show',
                    ],
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/{blueprint}',
                        'methods' => ['PUT'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\BlueprintController@update',
                        'name' => 'admin.v1.blueprints.update',
                    ],
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/{blueprint}',
                        'methods' => ['DELETE'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\BlueprintController@destroy',
                        'name' => 'admin.v1.blueprints.destroy',
                    ],
                    // Вспомогательные endpoints
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/{blueprint}/can-delete',
                        'methods' => ['GET'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\BlueprintController@canDelete',
                        'name' => 'admin.v1.blueprints.can-delete',
                    ],
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/{blueprint}/dependencies',
                        'methods' => ['GET'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\BlueprintController@dependencies',
                        'name' => 'admin.v1.blueprints.dependencies',
                    ],
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/{blueprint}/embeddable',
                        'methods' => ['GET'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\BlueprintController@embeddable',
                        'name' => 'admin.v1.blueprints.embeddable',
                    ],
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/{blueprint}/schema',
                        'methods' => ['GET'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\BlueprintController@schema',
                        'name' => 'admin.v1.blueprints.schema',
                    ],
                    // CRUD Path
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/{blueprint}/paths',
                        'methods' => ['GET'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\PathController@index',
                        'name' => 'admin.v1.blueprints.paths.index',
                    ],
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/{blueprint}/paths',
                        'methods' => ['POST'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\PathController@store',
                        'name' => 'admin.v1.blueprints.paths.store',
                    ],
                    // CRUD BlueprintEmbed
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/{blueprint}/embeds',
                        'methods' => ['GET'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\BlueprintEmbedController@index',
                        'name' => 'admin.v1.blueprints.embeds.index',
                    ],
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/{blueprint}/embeds',
                        'methods' => ['POST'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\BlueprintEmbedController@store',
                        'name' => 'admin.v1.blueprints.embeds.store',
                    ],
                ],
            ],
            // Path (глобальные операции)
            [
                'kind' => RouteNodeKind::GROUP,
                'prefix' => 'paths',
                'children' => [
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/{path}',
                        'methods' => ['GET'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\PathController@show',
                        'name' => 'admin.v1.paths.show',
                    ],
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/{path}',
                        'methods' => ['PUT'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\PathController@update',
                        'name' => 'admin.v1.paths.update',
                    ],
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/{path}',
                        'methods' => ['DELETE'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\PathController@destroy',
                        'name' => 'admin.v1.paths.destroy',
                    ],
                ],
            ],
            // BlueprintEmbed (глобальные операции)
            [
                'kind' => RouteNodeKind::GROUP,
                'prefix' => 'embeds',
                'children' => [
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/{embed}',
                        'methods' => ['GET'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\BlueprintEmbedController@show',
                        'name' => 'admin.v1.embeds.show',
                    ],
                    [
                        'kind' => RouteNodeKind::ROUTE,
                        'uri' => '/{embed}',
                        'methods' => ['DELETE'],
                        'action_type' => RouteNodeActionType::CONTROLLER,
                        'action' => 'App\Http\Controllers\Admin\V1\BlueprintEmbedController@destroy',
                        'name' => 'admin.v1.embeds.destroy',
                    ],
                ],
            ],
            // Route Nodes (full CRUD + reorder)
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/routes',
                'methods' => ['GET'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\RouteNodeController@index',
                'name' => 'admin.v1.routes.index',
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/routes',
                'methods' => ['POST'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\RouteNodeController@store',
                'name' => 'admin.v1.routes.store',
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/routes/reorder',
                'methods' => ['POST'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\RouteNodeController@reorder',
                'name' => 'admin.v1.routes.reorder',
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/routes/{id}',
                'methods' => ['GET'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\RouteNodeController@show',
                'name' => 'admin.v1.routes.show',
                'where' => ['id' => '[0-9]+'],
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/routes/{id}',
                'methods' => ['PATCH'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\RouteNodeController@update',
                'name' => 'admin.v1.routes.update',
                'where' => ['id' => '[0-9]+'],
            ],
            [
                'kind' => RouteNodeKind::ROUTE,
                'uri' => '/routes/{id}',
                'methods' => ['DELETE'],
                'action_type' => RouteNodeActionType::CONTROLLER,
                'action' => 'App\Http\Controllers\Admin\V1\RouteNodeController@destroy',
                'name' => 'admin.v1.routes.destroy',
                'where' => ['id' => '[0-9]+'],
            ],
        ],
    ],
];

