<?php

declare(strict_types=1);

namespace App\Support\Errors;

enum ErrorCode: string
{
    case BAD_REQUEST = 'BAD_REQUEST';
    case UNAUTHORIZED = 'UNAUTHORIZED';
    case FORBIDDEN = 'FORBIDDEN';
    case NOT_FOUND = 'NOT_FOUND';
    case VALIDATION_ERROR = 'VALIDATION_ERROR';
    case CONFLICT = 'CONFLICT';
    case RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED';
    case SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE';
    case INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';

    case INVALID_OPTION_IDENTIFIER = 'INVALID_OPTION_IDENTIFIER';
    case INVALID_OPTION_PAYLOAD = 'INVALID_OPTION_PAYLOAD';
    case INVALID_JSON_VALUE = 'INVALID_JSON_VALUE';
    case INVALID_OPTION_FILTERS = 'INVALID_OPTION_FILTERS';
    case INVALID_PLUGIN_MANIFEST = 'INVALID_PLUGIN_MANIFEST';
    case PLUGIN_ALREADY_DISABLED = 'PLUGIN_ALREADY_DISABLED';
    case PLUGIN_ALREADY_ENABLED = 'PLUGIN_ALREADY_ENABLED';
    case PLUGIN_NOT_FOUND = 'PLUGIN_NOT_FOUND';
    case ROUTES_RELOAD_FAILED = 'ROUTES_RELOAD_FAILED';

    case MEDIA_DOWNLOAD_ERROR = 'MEDIA_DOWNLOAD_ERROR';
    case MEDIA_VARIANT_ERROR = 'MEDIA_VARIANT_ERROR';

    case CSRF_TOKEN_MISMATCH = 'CSRF_TOKEN_MISMATCH';

}

